import * as THREE from 'three';
import {
  Fn, attributeArray, instanceIndex, vertexIndex, float, uniform, vec3, vec4,
  normalize, dot, abs, pow, sin, cos, mix, step,
  cameraPosition, normalWorld, positionWorld,
} from 'three/tsl';
import { evaluateMemoryFields } from './mission-memory.js';

const TAU = Math.PI * 2;

const clamp01 = value => Math.max(0, Math.min(1, value));
const hash = value => {
  const x = Math.sin(value * 127.1 + 311.7) * 43758.5453;
  return x - Math.floor(x);
};

/* Granite is dielectric, not metallic. The narrow return below is a
   view-dependent quartz/mica face reflection over a dark diffuse substrate;
   it does not emit light and vanishes when the facet turns away. */
function mineralMaterial(baseHex, glintHex) {
  const base = uniform(new THREE.Color(baseHex));
  const glint = uniform(new THREE.Color(glintHex));
  const material = new THREE.MeshBasicNodeMaterial();
  material.colorNode = Fn(() => {
    const view = normalize(cameraPosition.sub(positionWorld));
    const facing = abs(dot(normalize(normalWorld), view));
    const faceReturn = pow(facing, float(28)).mul(0.74);
    const grazing = pow(float(1).sub(facing), float(3.2)).mul(0.18);
    return vec4(base.mul(facing.mul(0.42).add(0.08))
      .add(glint.mul(faceReturn.add(grazing))), 1.0);
  })();
  return material;
}

function ring(radius, width, colour, opacity) {
  const mesh = new THREE.Mesh(
    new THREE.RingGeometry(radius - width * 0.5, radius + width * 0.5, 96),
    new THREE.MeshBasicMaterial({
      color: colour, transparent: true, opacity, depthWrite: false,
      blending: THREE.AdditiveBlending, side: THREE.DoubleSide,
    }),
  );
  mesh.rotation.x = -Math.PI / 2;
  return mesh;
}

/**
 * BODY 03 — GEOLOGICAL MEMORY
 *
 * Three grounded concordance sites are generated by MissionMemory. At each
 * site, BODY 01's eight material harmonics and BODY 02's hydration contour are
 * drawn as two slightly displaced ring families. Their visible beat is the
 * moiré. Quartz/mica facets and a density-changing particulate layer are the
 * other two measurements; there is no pickup icon or floating objective.
 */
export class GeologicalMemory {
  constructor({ renderer, heightAt, onComplete = null }) {
    this.renderer = renderer;
    this.heightAt = heightAt;
    this.onComplete = onComplete;
    this.group = new THREE.Group();
    this.group.visible = false;
    this.state = 'inactive';
    this.model = null;
    this.sites = [];
    this.current = 0;
    this.event = null;
    this.records = [];
    this.completedAt = 0;
    this.compute = null;
    this.computeDispatches = 0;
    this.particleCount = 0;
  }

  get active() { return this.state === 'searching' || this.state === 'scanning'; }
  get complete() { return this.state === 'complete'; }
  get target() { return this.active ? this.model?.sites?.[this.current] ?? null : null; }
  get scanFocus() { return this.event ? this.target : null; }

  _clearVisuals() {
    for (const root of [...this.group.children]) {
      root.traverse(node => {
        node.geometry?.dispose?.();
        if (Array.isArray(node.material)) node.material.forEach(material => material.dispose?.());
        else node.material?.dispose?.();
      });
      this.group.remove(root);
    }
    this.sites.length = 0;
    this.compute = null;
    this.particleCount = 0;
  }

  _buildSite(data, index) {
    const root = new THREE.Group();
    root.position.set(data.x, this.heightAt(data.x, data.z) + 0.035, data.z);
    root.rotation.y = data.phaseDelta * 0.18;
    root.userData.site = data;

    const materialRings = [], waterRings = [];
    const materialSpacing = 0.53 + (1 - data.coherence) * 0.16;
    const waterSpacing = materialSpacing * (1.035 + Math.abs(data.phaseDelta) * 0.014);
    for (let i = 1; i <= 10; i++) {
      const a = ring(i * materialSpacing, 0.014, 0xd9dde2, 0.032);
      a.position.set(-0.24, 0.004 + i * 0.00045, 0.08);
      a.scale.set(1, 0.72 + index * 0.035, 1);
      root.add(a); materialRings.push(a);

      const b = ring(i * waterSpacing, 0.012, 0x77aebc, 0.026);
      b.position.set(0.22, 0.010 + i * 0.00045, -0.10);
      b.scale.set(0.78 + index * 0.025, 1, 1);
      root.add(b); waterRings.push(b);
    }

    const mineralRoot = new THREE.Group();
    const quartz = mineralMaterial(0x343941, 0xd9eef2);
    const mica = mineralMaterial(0x2c2931, index === 2 ? 0xe6b44b : 0xc8b8d8);
    const shardGeometry = new THREE.OctahedronGeometry(0.16, 0);
    for (let i = 0; i < 15; i++) {
      const a = hash(index * 101 + i * 17) * Math.PI * 2;
      const r = 0.42 + hash(index * 131 + i * 23) * 3.8;
      const shard = new THREE.Mesh(shardGeometry, i % 4 === 0 ? mica : quartz);
      shard.position.set(Math.cos(a) * r, 0.035 + hash(i * 31 + index) * 0.12,
        Math.sin(a) * r * (0.68 + data.coherence * 0.18));
      shard.scale.set(0.42 + hash(i * 37) * 1.55,
        0.08 + hash(i * 41) * 0.22,
        0.36 + hash(i * 43) * 1.18);
      shard.rotation.set(hash(i * 47) * 1.8, a + data.phaseDelta, hash(i * 53) * 1.3);
      mineralRoot.add(shard);
    }
    root.add(mineralRoot);

    this.group.add(root);
    return { root, materialRings, waterRings, mineralRoot, data };
  }

  _buildParticleCompute() {
    const counts = this.model.sites.map(site => 96 + Math.round(site.density * 80));
    this.particleCount = counts.reduce((total, count) => total + count, 0);
    this.origin = attributeArray(this.particleCount, 'vec4');
    this.centre = attributeArray(this.particleCount, 'vec4');
    this.fieldData = attributeArray(this.particleCount, 'vec4');
    this.meta = attributeArray(this.particleCount, 'vec4');
    this.live = attributeArray(this.particleCount, 'vec4');
    const origin = this.origin.value.array, centre = this.centre.value.array;
    const fieldData = this.fieldData.value.array, meta = this.meta.value.array;
    let cursor = 0;
    for (let siteIndex = 0; siteIndex < this.model.sites.length; siteIndex++) {
      const site = this.model.sites[siteIndex];
      const cy = this.heightAt(site.x, site.z) + 0.035;
      for (let local = 0; local < counts[siteIndex]; local++, cursor++) {
        const p = cursor * 4, a = hash(siteIndex * 211 + local * 29) * TAU;
        const radius = 0.35 + hash(siteIndex * 223 + local * 31) * 4.8;
        const x = site.x + Math.cos(a) * radius;
        const y = cy + 0.04 + hash(siteIndex * 227 + local * 37) * 0.46;
        const z = site.z + Math.sin(a) * radius * 0.76;
        const fields = evaluateMemoryFields(this.model, x, z);
        origin.set([x, y, z, siteIndex], p);
        centre.set([site.x, cy, site.z, siteIndex], p);
        fieldData.set([
          fields.materialPhase, fields.waterPhase, fields.coherence, site.density,
        ], p);
        meta.set([
          hash(cursor * 41 + 7), hash(cursor * 43 + 13),
          hash(cursor * 47 + 29), hash(cursor * 53 + 31),
        ], p);
      }
    }
    for (const buffer of [this.origin, this.centre, this.fieldData, this.meta])
      buffer.value.needsUpdate = true;

    this.uTime = uniform(0);
    this.uCurrent = uniform(0);
    this.uIntegration = uniform(0);
    this.uMissionVisible = uniform(1);
    this.compute = Fn(() => {
      const i = instanceIndex;
      const base = this.origin.element(i);
      const centreAt = this.centre.element(i);
      const field = this.fieldData.element(i);
      const seed = this.meta.element(i);
      const current = float(1).sub(step(float(0.5), abs(base.w.sub(this.uCurrent))));
      const completed = step(base.w.add(0.5), this.uCurrent);
      /* These are the two transported scalar fields. Their product is a beat
         envelope: density rises only where material and hydration phases
         agree. The combination happens in storage compute, not on the CPU. */
      const materialScalar = sin(field.x.add(this.uTime.mul(0.13)).add(seed.x.mul(TAU)));
      const waterScalar = sin(field.y.sub(this.uTime.mul(0.081)).add(seed.y.mul(TAU)));
      const moire = materialScalar.mul(waterScalar).mul(0.5).add(0.5);
      const scan = this.uIntegration.mul(current);
      const contraction = float(1).sub(scan.mul(float(0.16).add(moire.mul(field.z).mul(0.15))));
      const radial = base.xyz.sub(centreAt.xyz);
      const phase = this.uTime.mul(float(0.20).add(seed.z.mul(0.08)))
        .add(moire.mul(TAU)).add(seed.w.mul(TAU));
      const position = centreAt.xyz.add(radial.mul(contraction)).add(vec3(
        cos(phase).mul(scan.mul(0.028)),
        sin(phase).mul(float(0.010).add(scan.mul(0.042))),
        sin(phase.add(1.7)).mul(scan.mul(0.028)),
      ));
      const latent = float(0.035).add(field.w.mul(0.08));
      const activeOpacity = latent.add(current.mul(float(0.09).add(scan.mul(0.25)))
        .add(moire.mul(field.z).mul(current).mul(0.08)));
      const opacity = mix(activeOpacity, float(0.022), completed).mul(this.uMissionVisible);
      this.live.element(i).assign(vec4(position, opacity));
    })().compute(this.particleCount);

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute('position', new THREE.BufferAttribute(new Float32Array(this.particleCount * 3), 3));
    const material = new THREE.PointsNodeMaterial({
      transparent: true, depthWrite: false, blending: THREE.NormalBlending,
      sizeAttenuation: true,
    });
    const live = this.live.element(vertexIndex);
    const field = this.fieldData.element(vertexIndex);
    const warm = vec3(0.73, 0.58, 0.29), cool = vec3(0.42, 0.67, 0.72);
    material.positionNode = live.xyz;
    material.sizeNode = float(0.020).add(field.z.mul(0.014));
    material.colorNode = vec4(mix(cool, warm, field.z.mul(0.72)), live.w);
    this.points = new THREE.Points(geometry, material);
    this.points.name = 'BODY03_MEMORY_GPU_FIELD';
    this.points.frustumCulled = false;
    this.group.add(this.points);
  }

  activate(model, now = performance.now()) {
    if (!model?.sites?.length) return false;
    this._clearVisuals();
    this.model = model;
    this.sites = model.sites.map((site, index) => this._buildSite(site, index));
    this._buildParticleCompute();
    this.current = 0;
    this.event = null;
    this.records = [];
    this.completedAt = 0;
    this.computeDispatches = 0;
    this.state = 'searching';
    this.startedAt = now;
    this.group.visible = true;
    return true;
  }

  reset() {
    this.state = 'inactive';
    this.model = null;
    this.current = 0;
    this.event = null;
    this.records = [];
    this.completedAt = 0;
    this.group.visible = false;
    this._clearVisuals();
  }

  shouldHold(probe) {
    const target = this.target;
    if (!target || !probe) return false;
    return Math.hypot(probe.x - target.x, probe.z - target.z) <= target.acquireRadius + 0.35;
  }

  forceAcquire(now = performance.now()) {
    if (!this.active) return false;
    this.event = { t0: now - this.target.scanHoldMs, forced: true };
    this._commit(now);
    return true;
  }

  _commit(now) {
    const site = this.target;
    if (!site) return;
    this.records.push(`${site.id} · ${site.objective} · ${(site.coherence * 100).toFixed(1)}% COHERENCE`);
    this.current++;
    this.event = null;
    if (this.current >= this.model.sites.length) {
      this.state = 'complete';
      this.completedAt = now;
      this.onComplete?.(this.snapshot(), now);
    } else this.state = 'searching';
  }

  async update(probe, now, worldActive = true) {
    this.group.visible = worldActive && this.state !== 'inactive';
    if (!this.group.visible) return;
    const t = now * 0.001;
    this.uTime.value = t;
    this.uCurrent.value = this.current;
    this.uMissionVisible.value = 1;
    this.uIntegration.value = this.event && this.target
      ? clamp01((now - this.event.t0) / this.target.scanHoldMs) : 0;
    for (let index = 0; index < this.sites.length; index++) {
      const site = this.sites[index], active = index === this.current;
      const completed = index < this.current;
      const integration = active && this.event
        ? clamp01((now - this.event.t0) / site.data.scanHoldMs) : 0;
      const beat = 0.72 + Math.sin(t * 0.42 + site.data.phaseDelta) * 0.28;
      for (let i = 0; i < site.materialRings.length; i++) {
        site.materialRings[i].material.opacity = completed ? 0.012
          : (active ? 0.045 + integration * 0.075 : 0.018) * beat;
        site.waterRings[i].material.opacity = completed ? 0.010
          : (active ? 0.038 + integration * 0.085 : 0.015) * (1.18 - beat * 0.34);
      }
      site.mineralRoot.visible = !completed;
    }

    if (this.compute && this.renderer?.computeAsync) {
      await this.renderer.computeAsync(this.compute);
      this.computeDispatches++;
    }

    if (!this.active) return;
    const target = this.target;
    const distance = Math.hypot(probe.x - target.x, probe.z - target.z);
    this.lastDistance = distance;
    if (this.event) {
      if (distance > target.scanRadius) {
        this.event = null; this.state = 'searching';
      } else if (now - this.event.t0 >= target.scanHoldMs) this._commit(now);
      return;
    }
    if (distance <= target.acquireRadius && probe.speed <= 0.12) {
      this.event = { t0: now };
      this.state = 'scanning';
    }
  }

  snapshot() {
    return {
      state: this.state,
      complete: this.complete,
      current: this.current,
      total: this.model?.sites?.length ?? 0,
      records: [...this.records],
      target: this.target ? {
        id: this.target.id, x: this.target.x, z: this.target.z,
        objective: this.target.objective, instruction: this.target.instruction,
      } : null,
      sources: this.model?.source ? { ...this.model.source } : null,
      gpu: {
        backend: 'webgpu-storage-compute',
        enabled: !!this.compute,
        particles: this.particleCount,
        dispatches: this.computeDispatches,
        fields: ['BODY01_MATERIAL_PHASE', 'BODY02_HYDRATION_PHASE'],
      },
    };
  }
}
