/**
 * FONT SUBSETTER — regenerates engine/fonts.css
 *
 *   npm run fonts
 *
 * Embeds DM Mono (300/400/500) and Space Mono (400/700), latin basic only,
 * plus a Noto Sans KR subset requested with the Google Fonts `&text=`
 * parameter containing EXACTLY the hangul syllables this work draws. That
 * subset is scraped from the source, so it can never drift from the captions
 * by accident — but it CAN go stale, so run this after editing Korean text.
 *
 * Everything is base64 woff2. A gallery machine cannot be assumed to have a
 * network, and a missing font is a silent failure that only shows up there.
 */

import { readFile, writeFile, readdir, stat } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const UA = { 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126 Safari/537.36' };

async function walk(dir, out = []) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) await walk(p, out);
    else if (/\.(js|html)$/.test(e.name)) out.push(p);
  }
  return out;
}

async function hangul() {
  /* scan the engine and every work — never the build output, which contains
     the whole bundle and would make the subset circular */
  const files = [...await walk(`${ROOT}/engine`), ...await walk(`${ROOT}/works`)];
  const set = new Set();
  for (const f of files) {
    for (const ch of await readFile(f, 'utf8')) {
      if (ch >= '\uac00' && ch <= '\ud7a3') set.add(ch);
    }
  }
  return [...set].sort().join('');
}

async function faces(query, text) {
  let url = 'https://fonts.googleapis.com/css2?' + query;
  if (text) url += '&text=' + encodeURIComponent(text);
  const css = await (await fetch(url, { headers: UA })).text();
  const out = [];
  for (const block of css.match(/@font-face\s*\{[^}]*\}/g) ?? []) {
    // for the latin faces keep only the basic-latin block; the subset request
    // returns exactly one block and must not be filtered
    if (!text && /unicode-range/.test(block) && !/U\+0000-00FF/.test(block)) continue;
    // NOTE: the &text= subset URL has no .woff2 suffix — do not match on one
    const m = block.match(/url\((https:\/\/[^)]+)\)/);
    if (!m) continue;
    const bytes = Buffer.from(await (await fetch(m[1], { headers: UA })).arrayBuffer());
    out.push({
      bytes: bytes.length,
      css: block.replace(m[1], `data:font/woff2;base64,${bytes.toString('base64')}`)
                .replace(/\s*unicode-range:[^;]+;/, ''),
    });
  }
  return out;
}

const ko = await hangul();
const all = [
  ...await faces('family=DM+Mono:wght@300;400;500&display=swap'),
  ...await faces('family=Space+Mono:wght@400;700&display=swap'),
  ...await faces('family=Noto+Sans+KR:wght@400&display=swap', ko),
];

const header = `/* Terra Incognita — fonts, inlined.
 *
 * Generated by tools/fonts.mjs. Do not edit by hand.
 * Korean subset: exactly ${ko.length} hangul syllables, scraped from source.
 * SUBSET: ${ko}
 *
 * REGENERATE AFTER CHANGING ANY KOREAN TEXT:  npm run fonts
 * A caption containing an unlisted syllable falls back to a system face
 * silently — and only on the gallery machine, where nobody is watching.
 */

`;

await writeFile(`${ROOT}/engine/fonts.css`, header + all.map(f => f.css).join('\n') + '\n');
const kb = (await stat(`${ROOT}/engine/fonts.css`)).size / 1024;
console.log(`✓ engine/fonts.css — ${all.length} faces, ${ko.length} hangul, ${kb.toFixed(1)} KB`);
